services:
  - type: web
    name: my-ecommerce-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: MONGO_URI=mongodb://127.0.0.1:27017/ecommerce
        sync: false
      - key: JWT_SECRET
        value: your_jwt_secret
        sync: false
      - key: MPESA_CONSUMER_KEY
        value: ynqO26FC5slp1bxMZbrzxSe6UhU6rXS7dg7lHW9u0OUDlt6YO
        sync: false
      - key: MPESA_CONSUMER_SECRET
        value: UFje6CJO8GmA9zsBYGWkdcGTM43KNupcEPstvUQIET4Q91rjiQUbwoqsAwaoqxnl
        sync: false
      - key: MPESA_SHORTCODE
        value: 174379
        sync: false
      - key: MPESA_PASSKEY
        value: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
        sync: false
      - key: MPESA_CALLBACK_URL
        value:  https://mydomain.com/path
        sync: false
      - key: MPESA_OAUTH_URL
        value: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
        sync: false
      - key: MPESA_STKPUSH_URL
        value: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
        sync: false
